export const categories = [
  buisnessForSale = [
    { name: "Business Services" },
    { name: "Government Businesses" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory Industrial Supplies" },
    { name: "Businesses for Rent" },
    { name: "Assets & Interiors" },
    { name: "Trade Licenses" },
    { name: "Electrical Equipments" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Office Furniture & Equipments" },
    { name: "Agriculture & Forestry" },
    { name: "Trade & Distribution" },
    { name: "Others" },
  ],
  sharesForSale = [
    { name: 'Running Businesses' },
    { name: 'Start-up Businesses' },
    { name: 'International Businesses' },
  ],
  businessIdeas = [
    { name: "Business Services" },
    { name: "Government Services" },
    { name: "AI" },
    { name: "Electronics" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Agriculture & Forestry" },
    { name: "Trade & Distribution" },
    { name: "Others" },
  ],
  investors = [
    { name: "Business Services" },
    { name: "Government Services" },
    { name: "AI" },
    { name: "Electronics" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Agriculture & Forestry" },
    { name: "Trade & Distribution" },
    { name: "Others" },
  ],
  InvestorsRequired = [
    { name: "Business Services" },
    { name: "Government Services" },
    { name: "AI" },
    { name: "Electronics" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Agriculture & Forestry" },
    { name: "Trade & Distribution" },
    { name: "Others" },
  ],
  franchiseOpportunities = [
    { name: "Business Services" },
    { name: "Government Services" },
    { name: "AI" },
    { name: "Electronics" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Agriculture & Forestry" },
    { name: "Trade & Distribution" },
    { name: "Others" },
  ],
  exportImportTrade = [
    { name: 'Manufacturer' },
    { name: 'Distributor' },
  ],
  MachinerySupplies = [
    { name: "Business Services" },
    { name: "Government Services" },
    { name: "ΑΙ" },
    { name: "Electronics" },
    { name: "Trading & Forex" },
    { name: "Real Estate" },
    { name: "Commercial" },
    { name: "Retail & Services" },
    { name: "Food & Beverage" },
    { name: "Industrial" },
    { name: "Healthcare & Laboratory" },
    { name: "Veterinary" },
    { name: "Manufacturing" },
    { name: "Marketing" },
    { name: "Garage & Workshops" },
    { name: "Construction" },
    { name: "Packaging & Shipping" },
    { name: "Agriculture & Forestry" },
    { name: "Industrial Supplies" },
    { name: "Assets & Interiors" },
    { name: "Electrical Equipments" },
    { name: "Garage & Workshops" },
    { name: "Office Furniture & Equipments" },
    { name: "Others" },
  ],
]